### ISSUE TITLE
Adding a schedule item sometimes causes an error (but not always)

### ISSUE THREAD

**Issue by nstoddard** [kirbyk/eventable#16]
This crash sometimes happens when adding a schedule item (but it doesn't always happen). I'm not sure what's going on.

```ruby
ActiveRecord::StatementInvalid in SchedulesController#create
SQLite3::ConstraintException: NOT NULL constraint failed: schedules.start_time: INSERT INTO "schedules" ("title", "description", "event_id", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?)

Extracted source (around line #19):
    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @event, notice: 'Schedule item successfully added to event.' }
      else
        format.html { render :new }

Rails.root: /home/nate/eventable

Application Trace | Framework Trace | Full Trace
app/controllers/schedules_controller.rb:19:in `block in create'
app/controllers/schedules_controller.rb:18:in `create'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"YaUTCBFYgRpw+hCqF8s7yh326TJFJ4/F1RVDRQ6XioTxL+vwTNP8PJiDWZKcN5Um1TeAsGvVuMWlfHHYp/G4Cg==",
 "schedule"=>{"title"=>"ab",
 "description"=>"b",
 "start_time"=>"11/17/2015 12:00 AM",
 "end_time"=>"11/26/2015 12:00 AM",
 "event_id"=>"1"},
 "commit"=>"Add Schedule Item"}
Toggle session dump
Toggle env dump
Response

Headers:

None
x
>>   
```

**Comment by kirbyk** [comment]
Fixed in [2a33bbd](https://github.com/kirbyk/eventable/commit/2a33bbd675bc778a7add44926b63b53f77505128).
